/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SanityImport } from './routes/sanity'

// Create/Update Routes

const SanityRoute = SanityImport.update({
  id: '/sanity',
  path: '/sanity',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sanity': {
      id: '/sanity'
      path: '/sanity'
      fullPath: '/sanity'
      preLoaderRoute: typeof SanityImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/sanity': typeof SanityRoute
}

export interface FileRoutesByTo {
  '/sanity': typeof SanityRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/sanity': typeof SanityRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sanity'
  fileRoutesByTo: FileRoutesByTo
  to: '/sanity'
  id: '__root__' | '/sanity'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SanityRoute: typeof SanityRoute
}

const rootRouteChildren: RootRouteChildren = {
  SanityRoute: SanityRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/sanity"
      ]
    },
    "/sanity": {
      "filePath": "sanity.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
